AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS-Demo (Playgorund)

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    
    LoggingConfig:
      LogFormat: JSON

Parameters:
  CognitoUserPoolID:
    Type: String
    Description: User Pool Name
    Default: us-east-2_yw6EaLWYa
  UserPoolArn:
    Type: String
    Description: User Pool ARN
    Default: arn:aws:cognito-idp:us-east-2:471112951175:userpool/us-east-2_yw6EaLWYa
  Region:
    Type: String
    Description: Region
    Default: us-east-2

Resources:
  AddFillUpHttpApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: AddFillUp
      StageName: Dev
      Description: Add fill up to the database
      Auth:
        DefaultAuthorizer: MyAuthorizer
        Authorizers:
          MyAuthorizer:
            UserPoolArn: !Ref UserPoolArn
            Identity:
              Header: Authorization

  AddFillUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FillUp
      CodeUri: demo/
      Handler: demo.app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
      - DynamoDBWritePolicy:
          TableName: FillUp
      - DynamoDBReadPolicy:
          TableName: FillUp
      Events:
        AddFillUpEvent:
          Type: Api
          Properties:
            Path: /fillup
            Method: POST
            RestApiId: !Ref AddFillUpHttpApi
        GetFillUpEvent:
          Type: Api
          Properties:
            Path: /fillup
            Method: GET
            RestApiId: !Ref AddFillUpHttpApi            

  FillUpTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: FillUp
      AttributeDefinitions:
        - AttributeName: userID
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: userID
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1