AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS-Demo (Playgorund)

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

    LoggingConfig:
      LogFormat: JSON
Resources:
  AddFillUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FillUp
      CodeUri: demo/
      Handler: demo.app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
      - DynamoDBWritePolicy:
          TableName: FillUp
  
  FillUpTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: FillUp
      AttributeDefinitions:
        - AttributeName: userID
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: userID
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
